### ISSUE TITLE
import sign_language_translator as slt throws error

### ISSUE THREAD

**Issue by Sourish0911** [sign-language-translator/sign-language-translator#28]
I installed sign-language-translator using pip install sign-language-translator

but when I try to import - - > 
import sign_language_translator as slt

This throws error - 
Python 3.9.18 (main, Sep 11 2023, 08:38:23) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sign_language_translator as slt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/abhinav/sign/sign-language-translator/sign_language_translator/__init__.py", line 66, in <module>
    from sign_language_translator import config, languages, models, text, utils, vision
  File "/Users/abhinav/sign/sign-language-translator/sign_language_translator/config/__init__.py", line 10, in <module>
    from sign_language_translator.config import enums, utils
  File "/Users/abhinav/sign/sign-language-translator/sign_language_translator/config/enums.py", line 22, in <module>
    from sign_language_translator.utils import (
  File "/Users/abhinav/sign/sign-language-translator/sign_language_translator/utils/__init__.py", line 21, in <module>
    from sign_language_translator.utils.archive import Archive
  File "/Users/abhinav/sign/sign-language-translator/sign_language_translator/utils/archive.py", line 18, in <module>
    from sign_language_translator.utils.utils import is_regex
  File "/Users/abhinav/sign/sign-language-translator/sign_language_translator/utils/utils.py", line 191, in <module>
    def is_regex(string: str | re.Pattern) -> bool:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
>>>

**Comment by mdsrqbl** [comment]
Hey,
Thanks a lot for bringing this to my attention.

Seems to be an issue with python version and type unions. I thought support was added for this after python 3.8 but seems i was wrong.

**For now, you may use `python >=3.10` and I'll patch this in the next release (v0.7.2) asap and add appropriate tests for it.**

Let me know if you face any other issues or have some suggestions. Appreciated 👍.

**Comment by Sourish0911** [comment]
Hi, 
I appreciate your quick response on this matter.
I works!!

**Comment by Sourish0911** [comment]
Thank you
